stages:
  - publish

publish:
  stage: publish
  tags:
    - moreillon
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - npm run build
    - npm publish
